config/routes.rb
Rails.application.routes.draw do

  #resources :performances
  get 'performances/:portfolio_id', to: 'performances#index', as: 'performance'

  resources :transactions
  resources :quotes
  get '/query/:ticker', to: 'quotes#query', defaults: { format: :json }

  resources :positions
  resources :securities

  resources :portfolios do
    member do
     get 'performance'
    end
  end

  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/position.rb
require 'csv'
class Position < ApplicationRecord

  belongs_to :portfolio
  belongs_to :security

  def self.import_csv(filename)

    portfolio_name = "default"
    portfolio = nil
    column_headers_valid = false
    date = DateTime.now
    asof_date = nil
    cash = nil

    lines = CSV.read(filename) unless filename.nil?
    lines.each do |line|
      next if line.empty?

      if column_headers_valid

      end

      case line[0]
        when /Positions for account (?<type>Individual|Joint)\s+(?<acct>XXXX-\d+) as of (?<date>.+)/i
          portfolio_name = Regexp.last_match(2)
          asof_date = DateTime.strptime( Regexp.last_match(3), '%H:%M %p %Z, %m/%d/%Y')
          print "Got account %s on %s\n" % [portfolio_name, asof_date.to_s]
          portfolio = Portfolio.find_or_create_by(:name=>portfolio_name,:user_id=>User.current.id)
        when  /Symbol/
          print "Got column header\n"
          # TODO: Validate column header expected keys
          columns_header_valid = true
        when /Account Total/
          print "Got account total\n"
        when /Cash & Money Market/
          cash = line[6].gsub(/[^\d\.-]/,'').to_f
          print "Got cash: %.2f\n" % [cash]
        else
          ticker = line[0]
          description = line[1]
          quantity = line[2]
          basis = line[9].gsub(/[^\d\.-]/,'').to_f
          type = line[15]
          print "Got %d %s for %.2f [%s]\n" % [quantity,ticker,basis,type]
          p = Position.new do |p|
            p.portfolio = portfolio
            p.security = Security.find_or_create_by(:ticker=>ticker)
            p.shares = quantity
            p.asof = asof_date
            p.basis = basis
          end
          p.save
      end
      portfolio.positions_asof = asof_date
      portfolio.save
    end
    portfolio.positions_asof = asof_date
    portfolio.cash = cash
    portfolio.save
    portfolio
  end

end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_position, only: [:show, :edit, :update, :destroy]

  # GET /positions
  # GET /positions.json
  def index
    @positions = Position.all
  end

  # GET /positions/1
  # GET /positions/1.json
  def show
  end

  # GET /positions/new
  def new
    @position = Position.new
  end

  # GET /positions/1/edit
  def edit
  end

  # POST /positions
  # POST /positions.json
  def create
    @position = Position.new(position_params)

    respond_to do |format|
      if @position.save
        format.html { redirect_to @position, notice: 'Position was successfully created.' }
        format.json { render :show, status: :created, location: @position }
      else
        format.html { render :new }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positions/1
  # PATCH/PUT /positions/1.json
  def update
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to @position, notice: 'Position was successfully updated.' }
        format.json { render :show, status: :ok, location: @position }
      else
        format.html { render :edit }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position.destroy
    respond_to do |format|
      format.html { redirect_to positions_url, notice: 'Position was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position
      @position = Position.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def position_params
      params.require(:position).permit(:portfolio, :security, :shares, :asof)
    end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_form.html.erb
<%= form_with(model: position, local: true) do |form| %>
  <% if position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
      <% position.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :portfolio %>
    <%= form.text_field :portfolio, id: :position_portfolio %>
  </div>

  <div class="field">
    <%= form.label :security %>
    <%= form.text_field :security, id: :position_security %>
  </div>

  <div class="field">
    <%= form.label :shares %>
    <%= form.text_field :shares, id: :position_shares %>
  </div>

  <div class="field">
    <%= form.label :asof %>
    <%= form.datetime_select :asof, id: :position_asof %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/positions/_show.html.erb
<tr>
  <td><%= position.security.ticker %></td>
  <td><%= position.shares %></td>
  <td><%= position.asof %></td>
  <td><%= link_to 'Show', position %></td>
  <td><%= link_to 'Edit', edit_position_path(position) %></td>
  <td><%= link_to 'Destroy', position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/positions/edit.html.erb
<h1>Editing Position</h1>

<%= render 'form', position: @position %>

<%= link_to 'Show', @position %> |
<%= link_to 'Back', positions_path %>

app/views/positions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Positions</h1>

<table>
  <thead>
    <tr>
      <th>Portfolio</th>
      <th>Security</th>
      <th>Shares</th>
      <th>Asof</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @positions.each do |position| %>
      <tr>
        <td><%= position.portfolio %></td>
        <td><%= position.security %></td>
        <td><%= position.shares %></td>
        <td><%= position.asof %></td>
        <td><%= link_to 'Show', position %></td>
        <td><%= link_to 'Edit', edit_position_path(position) %></td>
        <td><%= link_to 'Destroy', position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Position', new_position_path %>

app/views/positions/new.html.erb
<h1>New Position</h1>

<%= render 'form', position: @position %>

<%= link_to 'Back', positions_path %>

app/views/positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Portfolio:</strong>
  <%= @position.portfolio %>
</p>

<p>
  <strong>Security:</strong>
  <%= @position.security %>
</p>

<p>
  <strong>Shares:</strong>
  <%= @position.shares %>
</p>

<p>
  <strong>Asof:</strong>
  <%= @position.asof %>
</p>

<%= link_to 'Edit', edit_position_path(@position) %> |
<%= link_to 'Back', positions_path %>