config/routes.rb
Rails.application.routes.draw do

  #resources :performances
  get 'performances/:portfolio_id', to: 'performances#index', as: 'performance'

  resources :transactions
  resources :quotes
  get '/query/:ticker', to: 'quotes#query', defaults: { format: :json }

  resources :positions
  resources :securities

  resources :portfolios do
    member do
     get 'performance'
    end
  end

  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord

  belongs_to :user
  has_many :positions, dependent: :destroy
  has_many :transactions, dependent: :destroy

  before_create :init_label

  def init_label
    if label.nil?
      self.label = name
    end
  end

  def watched_positions

    # Construct a report
    return positions if positions.empty?

    d1 = self.positions_asof
    #d2 = self.transactions_end
    d2 = Date.today
    @performance = Performance.new(self,d1,d2)
    today = Date.today
    positions = @performance.relative_positions(today)
    positions
  end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_portfolio, only: [:show, :performance, :edit, :update, :destroy]

  # GET /portfolios
  # GET /portfolios.json
  def index
    @portfolios = Portfolio.where(:user => current_user)
  end

  # GET /portfolios/1
  # GET /portfolios/1.json
  def show
    @watched_positions = @portfolio.watched_positions
  end

  # GET /portfolios/1
  # GET /portfolios/1.json
  def performance

    d1 = Date.new(2017,1,1)
    d2 = Date.new(2018,2,20)

    @performance = Performance.new(@portfolio,d1,d2)

    @p = @performance
    @relative_positions_start = @p.relative_positions(@p.start_date)
    @relative_positions_end = @p.relative_positions(@p.end_date)

    # Render performance view

  end

  # GET /portfolios/new
  def new
    @portfolio = Portfolio.new
  end

  # GET /portfolios/1/edit
  def edit
  end

  # POST /portfolios
  # POST /portfolios.json
  def create

    file = portfolio_params["positions"]
    txfile = portfolio_params["transactions"]

    label = portfolio_params["label"]

    User.current = current_user
    @portfolio = Position.import_csv(file.path)

    @portfolio = Transaction.import_csv(txfile.path)

    #@portfolio = Portfolio.new(portfolio_params)
    #@portfolio.user = current_user
    @portfolio.label = label

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio }
      else
        format.html { render :new }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolios/1
  # PATCH/PUT /portfolios/1.json
  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio }
      else
        format.html { render :edit }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_params
      params.require(:portfolio).permit(:label, :positions, :transactions)
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_with(model: portfolio, local: true) do |form| %>
  <% if portfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

      <ul>
      <% portfolio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :label %>
    <%= form.text_field :label, id: :portfolio_label, class: "form-control" %>
  </div>

    <div class="form-group">
      <%= form.label :positions %>
      <%= form.file_field :positions, id: :portfolio_positions, class: "form-control-file" %>
    </div>

    <div class="form-group">
      <%= form.label :transactions %>
      <%= form.file_field :transactions, id: :portfolio_transactions, class: "form-control-file" %>
    </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Editing Portfolio</h1>

<%= render 'form', portfolio: @portfolio %>

<%= link_to 'Show', @portfolio %> |
<%= link_to 'Back', portfolios_path %>

app/views/portfolios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Portfolios</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Label</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @portfolios.each do |portfolio| %>
      <tr>
        <td><%= portfolio.name %></td>
        <td><%= portfolio.label %></td>
        <td><%= link_to 'Show', portfolio %></td>
        <td><%= link_to 'Edit', edit_portfolio_path(portfolio) %></td>
        <td><%= link_to 'Destroy', portfolio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Portfolio', new_portfolio_path %>

app/views/portfolios/new.html.erb
<h1>New Portfolio</h1>

<%= render 'form', portfolio: @portfolio %>

<%= link_to 'Back', portfolios_path %>

app/views/portfolios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= "%s (%s)" % [@portfolio.label, @portfolio.name] %>
</p>

<h1>Positions</h1>
<% unless @watched_positions.empty? %>
<%= render 'performances/relative_positions', positions: @watched_positions %>
<% else %>
<% end %>

<!--table id="portfolio-positions" class="table table-striped table-bordered">
  <thead>
  <tr>
    <th>Security</th>
    <th>Shares</th>
    <th>Asof</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <%= render :partial => 'positions/show', :collection => @portfolio.positions, :as => :position %>
  </tbody>
</table-->

<%= link_to 'Edit', edit_portfolio_path(@portfolio) %> |
<%= link_to 'Performance', performance_path(@portfolio) %> |
<%= link_to 'Back', portfolios_path %>